version: '3.8'

services:
  # Query Service
  query-service:
    build:
      context: ../query-service
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/service-account-key.json
      - BIGQUERY_PROJECT_ID=your-project-id
      - BIGQUERY_DATASET=your-dataset
      - HMAC_SECRET_SHARED=your_shared_hmac_secret_here
      - DEFAULT_TIMEZONE=America/New_York
      - PORT=3001
    ports:
      - "3001:3001"
    volumes:
      - ../sql:/app/sql:ro
      - ./credentials:/app/credentials:ro

  # Slack Bot
  slack-bot:
    build:
      context: ../slack-bot
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - SLACK_SIGNING_SECRET=your_slack_signing_secret_here
      - SLACK_BOT_TOKEN=xoxb-your_bot_token_here
      - SLACK_APP_TOKEN=xapp-your_app_token_here
      - ALLOWED_USERGROUP_ID=S123ABC
      - QUERY_SERVICE_URL=http://query-service:3001/api/top5
      - QUERY_SERVICE_HMAC_SECRET=your_shared_hmac_secret_here
      - DEFAULT_TIMEZONE=America/New_York
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      query-service:
        condition: service_started